MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: './checkpoints/jx_vit_base_p16_224-80ecf9dd.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'
  TYPE: 'vit'
  NO_MARGIN: True
  NAME: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [16, 16]
  JPM: True

INPUT:
  IMG_SIZE: [256, 256]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: 'bear'
  ROOT_DIR: './data/'
  IMG_DIR: './data/'
  OOD_DATA: True

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 60
  BASE_LR: 0.01
  IMS_PER_BATCH: 64
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 50
  LOG_PERIOD: 20
  EVAL_PERIOD: 100
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2

TEST:
  EVAL: True
  IMS_PER_BATCH: 64
  RE_RANKING: False
  WEIGHT: ''
  FEAT_NORM: 'yes'

