DATASETS:
  NAMES: 'bear'
MODEL:
  TYPE: swin
  NAME: swin_small_patch4_window7_224_22k
  DROP_PATH_RATE: 0.2
  POSE_WEIGHT: './checkpoints/pose/pose_hrnet_w32_bear_256x256_13kpts.pth'
  AGG_POSE_FEATURE: True
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7
SOLVER:
  MAX_EPOCHS: 60
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 5e-4
  BASE_LR: 0.01
  MOMENTUM: 0.9
  GAMMA: 0.1
  OPTIMIZER_NAME: 'SGD'
