DATASETS:
  IMG_SIZE: 384
MODEL:
  TYPE: swin
  NAME: swin_base_patch4_window12_384_finetune
  DROP_PATH_RATE: 0.5
  POSE_WEIGHT: './checkpoints/pose/pose_hrnet_w32_bear_256x256_13kpts.pth'
  AGG_POSE_FEATURE: True
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 12
SOLVER:
  MAX_EPOCHS: 30
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 1e-8
  BASE_LR: 2e-05
  WARMUP_LR: 2e-08
  MIN_LR: 2e-07
TEST:
  CROP: False