MODEL:
  TYPE: swin
  NAME: swin_base_patch4_window7_224
  DROP_PATH_RATE: 0.5
  POSE_WEIGHT: './checkpoints/pose/pose_hrnet_w32_bear_256x256_13kpts.pth'
  AGG_POSE_FEATURE: True
  SWIN:
    EMBED_DIM: 512
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 7