DATASETS:
  IMG_SIZE: 256
MODEL:
  TYPE: swin
  NAME: swin_tiny_c24_patch4_window8_256
  DROP_PATH_RATE: 0.2
  POSE_WEIGHT: './checkpoints/pose/pose_hrnet_w32_bear_256x256_13kpts.pth'
  AGG_POSE_FEATURE: True
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 8