DATASETS:
  IMG_SIZE: 256
MODEL:
  TYPE: swinv2
  NAME: swinv2_small_patch4_window16_256
  DROP_PATH_RATE: 0.3
  POSE_WEIGHT: './checkpoints/pose/pose_hrnet_w32_bear_256x256_13kpts.pth'
  AGG_POSE_FEATURE: True
  SWINV2:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 16